### ISSUE TITLE
`vagrant rsync` do nothing

### ISSUE THREAD

**Issue by histrio** [eucher/opennebula-provider#10]
Hi @eucher 
I've got a simple Vagrantfile with `config.vm.synced_folder ".", "/vagrant", type: "rsync"` inside.
`vagrant rsync` do not proceed synchronizing but `vagrant provision` do the job.

I tried to debug it myself with no luck.

Thanks!

**Comment by eucher** [comment]
Privet!

I have fixed it with new minor verison 1.1.0.
Plugin is using builtin function to sync from now. And syncing was moved to `vagrant up` and `vagrant reload` from `vagrant provision` commands.
Please upgrade and check.
