### ISSUE TITLE
Publish new version

### ISSUE THREAD

**Issue by prefer** [eucher/opennebula-provider#3]
Hello! Thanks for good stuff, we used it in the cloudlinux.
But we build gem from [last](https://github.com/eucher/opennebula-provider/commit/526e4c56e81b575e0012be6408332c4300f574e2) commit on the fog branch and upload from our server for access other staff. 
It's works very well for OpenNebula 4.14.2 in our case.
Could you publish new version (0.4.0) and upload it to [rubygems](https://rubygems.org/)?

**Comment by eucher** [comment]
Hello.
I want to publish a new version with fog support, when fog gem will be updated.
Current fog version has a debug output when processing suspend/resume commands.

**Comment by eucher** [comment]
It's too much time to wait. Published! Thanks!
