### ISSUE TITLE
Cannot execute vagrant ssh -c

### ISSUE THREAD

**Issue by Korulag** [eucher/opennebula-provider#5]
Vagrant supports executing commands via SSH, but when I'm trying to do so with VMs in OpenNebula, I'm receiving the following error:
vagrant ssh -c "uname -r"
Vagrant attempted to call the action 'ssh_run' on the provider
'#VagrantPlugins::OpenNebulaProvider::Provider:0x000000018c3ab0', but this provider doesn't support this action. This
is probably a bug in either the provider or the plugin calling this
action, and should be reported.

opennebula-provider version: 1.0.1
vagrant version: 1.8.4

**Comment by eucher** [comment]
Please check with 1.0.3
